/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package discordswing;

import javax.swing.SwingUtilities;
import java.awt.BorderLayout;
import java.awt.Container;

//my class import
import discordswing.guiskeleton.WindowFrame;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {

			public void run() {
				WindowFrame frame = new WindowFrame("hello");

				Container mainContainer = frame.getContentPane();
				mainContainer.setLayout(new BorderLayout());

			}
		});
    }
}
